name: starter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  analyzer: 6.2.0

dependencies:
  flutter_clearmind_archetype_app:
    path: ../../../flutter_clearmind_archetype/packages/app
  flutter_clearmind_archetype_shared:
    path: ../../../flutter_clearmind_archetype/packages/shared
  flutter_clearmind_archetype_domain:
    path: ../../../flutter_clearmind_archetype/packages/domain
  flutter_clearmind_archetype_resource:
    path: ../../../flutter_clearmind_archetype/packages/resource
  async: 2.11.0
#  auto_route: 7.8.4
  cached_network_image: 3.2.1
  cupertino_icons: 1.0.3
  dartx: 1.1.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_local_notifications: 12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.7
  go_router: 9.0.0
  infinite_scroll_pagination: 4.0.0
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  rxdart: 0.27.7
  tuple: 2.0.2
dev_dependencies:
#  auto_route_generator: 7.3.2
  bloc_test: 9.1.3
  build_runner: 2.4.5
  custom_lint: 0.5.0
  flutter_launcher_icons: 0.9.2
  flutter_lints: 2.0.1
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  logging: 1.1.1
  mocktail: 0.3.0
  nals_lints:
    path: ../nals_lints

#  fonts:
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400

flutter:
  uses-material-design: true