name: starter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  analyzer: 6.4.1

dependencies:
  flutter:
    sdk: flutter
  flutter_clearmind_archetype_app:
    path: ../../../flutter_clearmind_archetype/packages/app
  flutter_clearmind_archetype_shared:
    path: ../../../flutter_clearmind_archetype/packages/shared
  flutter_clearmind_archetype_domain:
    path: ../../../flutter_clearmind_archetype/packages/domain
  flutter_clearmind_archetype_resource:
    path: ../../../flutter_clearmind_archetype/packages/resource
  app:
    path: ../app
  data:
    path: ../data
  domain:
    path: ../domain
  resources:
    path: ../resources
  async: 2.11.0
#  auto_route: 7.8.4
  flutter_localizations:
    sdk: flutter
dev_dependencies:
#  auto_route_generator: 7.3.2
  custom_lint: ^0.6.2
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 2.2.16
  nals_lints:
    path: ../nals_lints

#  fonts:
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400

flutter:
  uses-material-design: true