name: app
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 6.4.1

dependencies:
  flutter:
    sdk: flutter
  flutter_clearmind_archetype_app:
    path: ../../../flutter_clearmind_archetype/packages/app
  flutter_clearmind_archetype_shared:
    path: ../../../flutter_clearmind_archetype/packages/shared
  flutter_clearmind_archetype_domain:
    path: ../../../flutter_clearmind_archetype/packages/domain
  flutter_clearmind_archetype_resource:
    path: ../../../flutter_clearmind_archetype/packages/resource
  flutter_clearmind_widget:
    path: ../../../flutter_clearmind_library/packages/flutter_clearmind_widget
  flutter_clearmind_widget_external:
    path: ../../../flutter_clearmind_library/packages/flutter_clearmind_widget_external
  async: 2.11.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartx: ^1.2.0
  domain:
    path: ../domain
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  infinite_scroll_pagination: 4.0.0
  resources:
    path: ../resources
  rxdart: 0.27.7
  tuple: 2.0.2
  flutter_screenutil: ^5.9.1
  # icon
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 2.2.16
  freezed: 2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
  logging: ^1.2.0
  mocktail: ^1.0.3
  nals_lints:
    path: ../nals_lints

flutter:
