name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 6.4.1

dependencies:
  flutter_clearmind_archetype_domain:
    path: ../../../flutter_clearmind_archetype/packages/domain
  flutter_clearmind_archetype_shared:
    path: ../../../flutter_clearmind_archetype/packages/shared
  flutter:
    sdk: flutter
  resources:
    path: ../resources

dev_dependencies:
  build_runner: 2.4.5
  custom_lint: ^0.6.2
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  json_serializable: 6.7.0
  logging: 1.1.1
  mocktail: 0.3.0
  nals_lints:
    path: ../nals_lints
