name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 6.4.1

dependencies:
  flutter_clearmind_archetype_domain:
    path: ../../../flutter_clearmind_archetype/packages/domain
  flutter_clearmind_archetype_shared:
    path: ../../../flutter_clearmind_archetype/packages/shared
  flutter:
    sdk: flutter
  resources:
    path: ../resources

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: 6.7.0
  logging: ^1.2.0
  mocktail: ^1.0.3
  nals_lints:
    path: ../nals_lints
